import type {
  User,
  Report,
  Proposal,
  Project,
  Notification,
  Activity,
  DashboardStats,
  Badge,
  SimulationScenario,
  MapLayer,
  Comment,
} from "@/types";

// ============================
// Users
// ============================

export const mockBadges: Badge[] = [
  { id: "b1", name: "Primul Raport", description: "Ai trimis primul tău raport", icon: "🏅", earned: true, earnedAt: "2025-11-10" },
  { id: "b2", name: "Activist Urban", description: "10 rapoarte trimise", icon: "🌟", earned: true, earnedAt: "2025-12-15" },
  { id: "b3", name: "Voce Civică", description: "5 propuneri trimise", icon: "📢", earned: false },
  { id: "b4", name: "Campion Civic", description: "50 rapoarte trimise", icon: "🏆", earned: false },
  { id: "b5", name: "Explorator", description: "Rapoarte din 5 cartiere diferite", icon: "🗺️", earned: true, earnedAt: "2026-01-20" },
  { id: "b6", name: "Comentator Activ", description: "20 comentarii la propuneri", icon: "💬", earned: false },
];

export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Andrei Popescu",
    email: "andrei.popescu@email.com",
    role: "cetatean",
    avatar: "",
    neighborhood: "Mănăștur",
    joinedAt: "2025-09-15",
    xp: 1250,
    level: 3,
    levelName: "Activist Urban",
    badges: [mockBadges[0], mockBadges[1], mockBadges[4]],
  },
  {
    id: "u2",
    name: "Maria Ionescu",
    email: "maria.ionescu@email.com",
    role: "cetatean",
    avatar: "",
    neighborhood: "Centru",
    joinedAt: "2025-10-20",
    xp: 830,
    level: 2,
    levelName: "Biciclist Activ",
    badges: [mockBadges[0]],
  },
  {
    id: "u3",
    name: "Mihai Dumitru",
    email: "mihai.dumitru@email.com",
    role: "cetatean",
    avatar: "",
    neighborhood: "Gheorgheni",
    joinedAt: "2026-01-05",
    xp: 420,
    level: 1,
    levelName: "Începător",
    badges: [mockBadges[0]],
  },
  {
    id: "admin1",
    name: "Admin Cluj-Napoca",
    email: "admin@clujnapoca.ro",
    role: "admin",
    avatar: "",
    neighborhood: "Centru",
    joinedAt: "2025-01-01",
    xp: 0,
    level: 0,
    levelName: "Administrator",
    badges: [],
  },
];

export const currentUser = mockUsers[0];

// ============================
// Reports
// ============================

export const reportCategoryLabels: Record<string, string> = {
  masini_parcate: "Mașini parcate pe piste",
  gropi: "Gropi / deteriorări",
  constructii: "Construcții blocante",
  drum_blocat: "Drum blocat",
  interferenta_pietoni: "Interferență cu pietonii",
  obstacole: "Obstacole pe drumuri",
  parcari_biciclete: "Parcări de biciclete proaste",
  iluminat: "Iluminat insuficient",
  altele: "Altele",
};

export const reportCategoryIcons: Record<string, string> = {
  masini_parcate: "🚗",
  gropi: "🕳️",
  constructii: "🚧",
  drum_blocat: "🚫",
  interferenta_pietoni: "🚶",
  obstacole: "⚠️",
  parcari_biciclete: "🅿️",
  iluminat: "🔦",
  altele: "📍",
};

export const mockReports: Report[] = [
  {
    id: "r1",
    userId: "u1",
    category: "masini_parcate",
    categoryLabel: "Mașini parcate pe piste",
    severity: "ridicat",
    status: "in_analiza",
    title: "SUV parcat pe pista de pe Calea Moților",
    description: "Un SUV negru este parcat permanent pe pista de biciclete de pe Calea Moților, în dreptul numărului 42. Forțează bicicliștii să circule pe carosabil.",
    location: { lat: 46.7712, lng: 23.5897 },
    address: "Calea Moților 42, Cluj-Napoca",
    photos: [],
    seenCount: 3,
    createdAt: "2026-03-08T10:30:00Z",
    updatedAt: "2026-03-08T10:30:00Z",
  },
  {
    id: "r2",
    userId: "u1",
    category: "gropi",
    categoryLabel: "Gropi / deteriorări",
    severity: "mediu",
    status: "trimis",
    title: "Groapă mare pe strada Memorandumului",
    description: "Groapă adâncă de aproximativ 15cm pe pista de biciclete, aproape de intersecția cu strada Eroilor. Pericol de accident.",
    location: { lat: 46.7695, lng: 23.5880 },
    address: "Strada Memorandumului, Cluj-Napoca",
    photos: [],
    seenCount: 5,
    createdAt: "2026-03-07T14:20:00Z",
    updatedAt: "2026-03-07T14:20:00Z",
  },
  {
    id: "r3",
    userId: "u2",
    category: "iluminat",
    categoryLabel: "Iluminat insuficient",
    severity: "ridicat",
    status: "in_lucru",
    title: "Lipsă iluminat pe tronsonul Parcul Central",
    description: "Segmentul de pistă de biciclete din Parcul Central nu are iluminat funcțional pe o distanță de aproximativ 200m. Foarte periculos seara.",
    location: { lat: 46.7710, lng: 23.5960 },
    address: "Parcul Central, Cluj-Napoca",
    photos: [],
    seenCount: 8,
    createdAt: "2026-03-05T18:45:00Z",
    updatedAt: "2026-03-09T09:15:00Z",
  },
  {
    id: "r4",
    userId: "u3",
    category: "constructii",
    categoryLabel: "Construcții blocante",
    severity: "critic",
    status: "in_analiza",
    title: "Schele pe toată lățimea trotuarului pe Bulevardul Eroilor",
    description: "Lucrări de renovare a fațadei au blocat complet trotuarul și pista de biciclete. Nu există rută alternativă semnalizată.",
    location: { lat: 46.7705, lng: 23.5870 },
    address: "Bulevardul Eroilor 15, Cluj-Napoca",
    photos: [],
    seenCount: 12,
    createdAt: "2026-03-06T08:00:00Z",
    updatedAt: "2026-03-06T08:00:00Z",
  },
  {
    id: "r5",
    userId: "u1",
    category: "obstacole",
    categoryLabel: "Obstacole pe drumuri",
    severity: "mediu",
    status: "rezolvat",
    title: "Tomberon lăsat pe pistă pe strada Napoca",
    description: "Un tomberon de gunoi a fost lăsat pe pista de biciclete de personalul de salubrizare.",
    location: { lat: 46.7725, lng: 23.5915 },
    address: "Strada Napoca, Cluj-Napoca",
    photos: [],
    seenCount: 2,
    createdAt: "2026-03-01T07:30:00Z",
    updatedAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "r6",
    userId: "u2",
    category: "drum_blocat",
    categoryLabel: "Drum blocat",
    severity: "ridicat",
    status: "trimis",
    title: "Livrare blocheaza pista pe Eroilor",
    description: "Camion de livrare parcat zilnic între orele 8-10 pe pista de biciclete, lângă magazinul alimentar.",
    location: { lat: 46.7700, lng: 23.5855 },
    address: "Bulevardul Eroilor 30, Cluj-Napoca",
    photos: [],
    seenCount: 6,
    createdAt: "2026-03-09T09:00:00Z",
    updatedAt: "2026-03-09T09:00:00Z",
  },
  {
    id: "r7",
    userId: "u3",
    category: "interferenta_pietoni",
    categoryLabel: "Interferență cu pietonii",
    severity: "scazut",
    status: "trimis",
    title: "Pietoni pe pista de pe Republicii",
    description: "Mulți pietoni merg pe pista de biciclete de pe strada Republicii, probabil din cauza marcajelor insuficiente.",
    location: { lat: 46.7715, lng: 23.5930 },
    address: "Strada Republicii, Cluj-Napoca",
    photos: [],
    seenCount: 4,
    createdAt: "2026-03-08T16:00:00Z",
    updatedAt: "2026-03-08T16:00:00Z",
  },
  {
    id: "r8",
    userId: "u1",
    category: "parcari_biciclete",
    categoryLabel: "Parcări de biciclete proaste",
    severity: "mediu",
    status: "in_analiza",
    title: "Suporturi biciclete ruginite la Universitate",
    description: "Suporturile de biciclete din fața Universității Babeș-Bolyai sunt puternic ruginite și instabile. Riscul de deteriorare a bicicletelor este ridicat.",
    location: { lat: 46.7670, lng: 23.5910 },
    address: "Universitatea Babeș-Bolyai, Cluj-Napoca",
    photos: [],
    seenCount: 3,
    createdAt: "2026-03-04T12:15:00Z",
    updatedAt: "2026-03-04T12:15:00Z",
  },
  {
    id: "r9",
    userId: "u2",
    category: "masini_parcate",
    categoryLabel: "Mașini parcate pe piste",
    severity: "ridicat",
    status: "in_lucru",
    title: "Parcare neautorizată pe pista de pe Dorobanților",
    description: "Mai multe mașini parcate permanent pe pista de biciclete de pe strada Dorobanților, în zona blocurilor.",
    location: { lat: 46.7650, lng: 23.5850 },
    address: "Strada Dorobanților, Cluj-Napoca",
    photos: [],
    seenCount: 10,
    createdAt: "2026-02-28T11:00:00Z",
    updatedAt: "2026-03-07T14:30:00Z",
  },
  {
    id: "r10",
    userId: "u3",
    category: "gropi",
    categoryLabel: "Gropi / deteriorări",
    severity: "ridicat",
    status: "trimis",
    title: "Asfalt crăpat pe pista din Gheorgheni",
    description: "Asfaltul pistei de biciclete din zona Gheorgheni prezintă multiple crăpături și denivelări pe o distanță de circa 100m.",
    location: { lat: 46.7680, lng: 23.6050 },
    address: "Aleea Carpați, Gheorgheni, Cluj-Napoca",
    photos: [],
    seenCount: 7,
    createdAt: "2026-03-10T08:45:00Z",
    updatedAt: "2026-03-10T08:45:00Z",
  },
  {
    id: "r11",
    userId: "u1",
    category: "iluminat",
    categoryLabel: "Iluminat insuficient",
    severity: "mediu",
    status: "trimis",
    title: "Bec ars pe pista de pe malul Someșului",
    description: "Trei stâlpi de iluminat consecutivi nu funcționează pe pista de pe malul Someșului, zona Grigorescu.",
    location: { lat: 46.7730, lng: 23.5780 },
    address: "Malul Someșului, Grigorescu, Cluj-Napoca",
    photos: [],
    seenCount: 2,
    createdAt: "2026-03-09T19:30:00Z",
    updatedAt: "2026-03-09T19:30:00Z",
  },
  {
    id: "r12",
    userId: "u2",
    category: "obstacole",
    categoryLabel: "Obstacole pe drumuri",
    severity: "scazut",
    status: "rezolvat",
    title: "Ramuri căzute pe pistă în Parcul Cetățuie",
    description: "Mai multe ramuri de copac au căzut pe pista de biciclete din Parcul Cetățuie după furtuna de ieri.",
    location: { lat: 46.7740, lng: 23.5860 },
    address: "Parcul Cetățuie, Cluj-Napoca",
    photos: [],
    seenCount: 1,
    createdAt: "2026-02-25T10:00:00Z",
    updatedAt: "2026-02-26T08:00:00Z",
  },
  {
    id: "r13",
    userId: "u1",
    category: "constructii",
    categoryLabel: "Construcții blocante",
    severity: "mediu",
    status: "in_analiza",
    title: "Excavator parcat pe pistă pe Fabricii",
    description: "Utilaj de construcții parcat pe pista de biciclete în zona lucrărilor de pe strada Fabricii. Trebuie deviere.",
    location: { lat: 46.7760, lng: 23.5820 },
    address: "Strada Fabricii, Cluj-Napoca",
    photos: [],
    seenCount: 4,
    createdAt: "2026-03-07T07:45:00Z",
    updatedAt: "2026-03-07T07:45:00Z",
  },
  {
    id: "r14",
    userId: "u3",
    category: "masini_parcate",
    categoryLabel: "Mașini parcate pe piste",
    severity: "mediu",
    status: "trimis",
    title: "Taxi-uri parcate pe pista la gară",
    description: "Taxiurile staționează regulat pe pista de biciclete din fața Gării Cluj-Napoca.",
    location: { lat: 46.7810, lng: 23.5940 },
    address: "Piața Gării, Cluj-Napoca",
    photos: [],
    seenCount: 9,
    createdAt: "2026-03-10T06:30:00Z",
    updatedAt: "2026-03-10T06:30:00Z",
  },
  {
    id: "r15",
    userId: "u2",
    category: "altele",
    categoryLabel: "Altele",
    severity: "scazut",
    status: "trimis",
    title: "Marcaje pistă șterse pe Observatorului",
    description: "Marcajele pistei de biciclete de pe strada Observatorului sunt aproape complet șterse și nu mai sunt vizibile.",
    location: { lat: 46.7635, lng: 23.5985 },
    address: "Strada Observatorului, Cluj-Napoca",
    photos: [],
    seenCount: 3,
    createdAt: "2026-03-06T15:20:00Z",
    updatedAt: "2026-03-06T15:20:00Z",
  },
];

// ============================
// Proposals
// ============================

const mockComments: Comment[] = [
  {
    id: "c1",
    userId: "u2",
    authorName: "Maria Ionescu",
    content: "Excelentă idee! Această zonă are nevoie urgentă de o pistă dedicată.",
    createdAt: "2026-03-06T12:00:00Z",
    replies: [
      {
        id: "c1r1",
        userId: "u1",
        authorName: "Andrei Popescu",
        content: "De acord! Eu circul zilnic pe acest traseu și este foarte periculos.",
        createdAt: "2026-03-06T13:30:00Z",
        replies: [],
      },
    ],
  },
  {
    id: "c2",
    userId: "u3",
    authorName: "Mihai Dumitru",
    content: "Ar fi grozav dacă s-ar face legătura cu pista din Gheorgheni.",
    createdAt: "2026-03-07T09:00:00Z",
    replies: [],
  },
];

export const proposalCategoryLabels: Record<string, string> = {
  pista_noua: "Pistă nouă",
  parcare_biciclete: "Parcare biciclete",
  siguranta: "Siguranță",
  semaforizare: "Semaforizare",
  infrastructura_verde: "Infrastructură verde",
  altele: "Altele",
};

export const mockProposals: Proposal[] = [
  {
    id: "p1",
    userId: "u1",
    authorName: "Andrei Popescu",
    category: "pista_noua",
    categoryLabel: "Pistă nouă",
    title: "Pistă de biciclete pe Calea Turzii",
    description: "Propun construirea unei piste dedicate de biciclete pe Calea Turzii, de la intersecția cu strada Observatorului până la ieșirea din oraș. Aceasta ar conecta cartierul Mănăștur cu zona de sud a orașului și ar oferi o alternativă sigură pentru cei care fac naveta.",
    location: { lat: 46.7580, lng: 23.5870 },
    address: "Calea Turzii, Cluj-Napoca",
    images: [],
    votes: 142,
    userVote: null,
    commentCount: 3,
    comments: mockComments,
    status: "in_analiza",
    createdAt: "2026-03-01T10:00:00Z",
  },
  {
    id: "p2",
    userId: "u2",
    authorName: "Maria Ionescu",
    category: "parcare_biciclete",
    categoryLabel: "Parcare biciclete",
    title: "Stații de biciclete securizate la stațiile de autobuz",
    description: "Instalarea de parcări securizate pentru biciclete la toate stațiile importante de transport public din Cluj-Napoca. Aceasta ar facilita transportul intermodal bicicletă-autobuz.",
    location: { lat: 46.7712, lng: 23.5897 },
    address: "Centrul Civic, Cluj-Napoca",
    images: [],
    votes: 98,
    userVote: "up",
    commentCount: 1,
    comments: [mockComments[0]],
    status: "aprobat",
    createdAt: "2026-02-15T14:00:00Z",
  },
  {
    id: "p3",
    userId: "u3",
    authorName: "Mihai Dumitru",
    category: "siguranta",
    categoryLabel: "Siguranță",
    title: "Oglinzi de trafic la intersecțiile din Gheorgheni",
    description: "Montarea de oglinzi de trafic la intersecțiile periculoase din cartierul Gheorgheni, unde vizibilitatea este redusă pentru bicicliști din cauza gardurilor și vegetației.",
    location: { lat: 46.7680, lng: 23.6050 },
    address: "Gheorgheni, Cluj-Napoca",
    images: [],
    votes: 67,
    userVote: null,
    commentCount: 0,
    comments: [],
    status: "in_analiza",
    createdAt: "2026-03-05T11:30:00Z",
  },
  {
    id: "p4",
    userId: "u1",
    authorName: "Andrei Popescu",
    category: "semaforizare",
    categoryLabel: "Semaforizare",
    title: "Semafoare dedicate bicicliștilor pe Eroilor",
    description: "Instalarea de semafoare specifice pentru bicicliști pe Bulevardul Eroilor, cu fază separată care să permită traversarea în siguranță a intersecțiilor principale.",
    location: { lat: 46.7700, lng: 23.5870 },
    address: "Bulevardul Eroilor, Cluj-Napoca",
    images: [],
    votes: 113,
    userVote: "up",
    commentCount: 2,
    comments: mockComments,
    status: "in_implementare",
    createdAt: "2026-01-20T09:00:00Z",
  },
  {
    id: "p5",
    userId: "u2",
    authorName: "Maria Ionescu",
    category: "infrastructura_verde",
    categoryLabel: "Infrastructură verde",
    title: "Coridor verde pe malul Someșului",
    description: "Crearea unui coridor verde continuu pe malul Someșului, cu pistă de biciclete, vegetație și zone de odihnă. Ar conecta cartierul Grigorescu cu zona centrală.",
    location: { lat: 46.7730, lng: 23.5780 },
    address: "Malul Someșului, Cluj-Napoca",
    images: [],
    votes: 189,
    userVote: null,
    commentCount: 5,
    comments: [...mockComments, ...mockComments.map(c => ({...c, id: c.id + "_dup"}))].slice(0, 5),
    status: "in_analiza",
    createdAt: "2026-02-10T16:00:00Z",
  },
  {
    id: "p6",
    userId: "u3",
    authorName: "Mihai Dumitru",
    category: "siguranta",
    categoryLabel: "Siguranță",
    title: "Bariere fizice între pistă și carosabil pe Dorobanților",
    description: "Propun instalarea de bariere fizice (stâlpi flexibili sau jardiniere) între pista de biciclete și banda de circulație auto pe strada Dorobanților.",
    location: { lat: 46.7650, lng: 23.5850 },
    address: "Strada Dorobanților, Cluj-Napoca",
    images: [],
    votes: 76,
    userVote: null,
    commentCount: 1,
    comments: [mockComments[1]],
    status: "respins",
    createdAt: "2026-02-25T08:00:00Z",
  },
  {
    id: "p7",
    userId: "u1",
    authorName: "Andrei Popescu",
    category: "pista_noua",
    categoryLabel: "Pistă nouă",
    title: "Rută ciclabilă campus universitar",
    description: "Conectarea campusurilor universitare (UBB, UTCN, UMF) printr-o rută ciclabilă dedicată, cu parcări securizate la fiecare campus.",
    location: { lat: 46.7670, lng: 23.5910 },
    address: "Campus Universitar, Cluj-Napoca",
    images: [],
    votes: 204,
    userVote: "up",
    commentCount: 4,
    comments: [...mockComments, ...mockComments.map(c => ({...c, id: c.id + "_dup2"}))].slice(0, 4),
    status: "aprobat",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: "p8",
    userId: "u2",
    authorName: "Maria Ionescu",
    category: "altele",
    categoryLabel: "Altele",
    title: "Aplicație mobilă pentru raportare rapidă",
    description: "Dezvoltarea unei aplicații mobile companion pentru VeloCivic care să permită raportarea rapidă a problemelor direct de pe telefon, cu geolocalizare automată.",
    location: { lat: 46.7712, lng: 23.5897 },
    address: "Cluj-Napoca",
    images: [],
    votes: 156,
    userVote: null,
    commentCount: 3,
    comments: [...mockComments, { id: "cx", userId: "u3", authorName: "Mihai Dumitru", content: "Ar fi foarte util! Acum e greu să raportezi probleme în timp ce pedalezi.", createdAt: "2026-03-08T10:00:00Z", replies: [] }],
    status: "in_analiza",
    createdAt: "2026-03-02T12:00:00Z",
  },
];

// ============================
// Projects
// ============================

export const mockProjects: Project[] = [
  {
    id: "pr1",
    title: "Rețea ciclabilă centru Cluj-Napoca",
    description: "Proiect amplu de creare a unei rețele integrate de piste de biciclete în centrul istoric al Cluj-Napocii. Va include 12km de piste noi, 200 de locuri de parcare pentru biciclete și 15 intersecții cu semaforizare dedicată.",
    image: "",
    stage: "in_lucru",
    stageLabel: "În lucru",
    budget: "4.500.000 RON",
    timeline: "Iunie 2026 - Decembrie 2027",
    team: "Direcția Tehnică, Departamentul Transport",
    location: { lat: 46.7712, lng: 23.5897 },
    address: "Centrul Istoric, Cluj-Napoca",
    followers: 1234,
    isFollowing: true,
    likes: 567,
    commentCount: 45,
    comments: mockComments,
    citizenEngagementScore: 87,
    createdAt: "2025-06-01T10:00:00Z",
    updatedAt: "2026-03-08T16:00:00Z",
  },
  {
    id: "pr2",
    title: "Parcări inteligente pentru biciclete",
    description: "Instalarea a 50 de stații inteligente de parcare pentru biciclete în punctele cheie ale orașului: stații de autobuz, piețe, instituții publice și centre comerciale. Fiecare stație va avea sistem de închidere electronic și monitorizare video.",
    image: "",
    stage: "aprobare",
    stageLabel: "Aprobare",
    budget: "1.200.000 RON",
    timeline: "Septembrie 2026 - Martie 2027",
    team: "Smart City Department",
    location: { lat: 46.7700, lng: 23.5870 },
    address: "Diverse locații, Cluj-Napoca",
    followers: 890,
    isFollowing: false,
    likes: 345,
    commentCount: 23,
    comments: [mockComments[0]],
    citizenEngagementScore: 72,
    createdAt: "2025-12-15T10:00:00Z",
    updatedAt: "2026-02-20T14:00:00Z",
  },
  {
    id: "pr3",
    title: "Coridor verde Someș - de la Grigorescu la Expo",
    description: "Crearea unui coridor verde continuu pe ambele maluri ale Someșului, de la cartierul Grigorescu până la zona Expo Transilvania. Va include pistă de biciclete bidirectională, zonă pietonală, spații verzi și mobilier urban.",
    image: "",
    stage: "consultare_publica",
    stageLabel: "Consultare publică",
    budget: "8.900.000 RON",
    timeline: "2027 - 2029",
    team: "Arhitectul Șef, Direcția Mediu",
    location: { lat: 46.7730, lng: 23.5780 },
    address: "Malul Someșului, Cluj-Napoca",
    followers: 2100,
    isFollowing: true,
    likes: 890,
    commentCount: 78,
    comments: mockComments,
    citizenEngagementScore: 94,
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2026-03-10T10:00:00Z",
  },
  {
    id: "pr4",
    title: "Bike-sharing electric Cluj",
    description: "Lansarea unui sistem de bike-sharing cu biciclete electrice. 500 de biciclete în 80 de stații acoperind toate cartierele principale. Aplicație mobilă dedicată cu plată integrată.",
    image: "",
    stage: "planificat",
    stageLabel: "Planificat",
    budget: "6.200.000 RON",
    timeline: "2027 - 2028",
    team: "Direcția Transport Public",
    location: { lat: 46.7712, lng: 23.5897 },
    address: "Cluj-Napoca",
    followers: 3200,
    isFollowing: false,
    likes: 1200,
    commentCount: 92,
    comments: [...mockComments, { id: "cp1", userId: "u3", authorName: "Mihai Dumitru", content: "Abia aștept! Ar fi genial pentru naveta zilnică.", createdAt: "2026-03-09T10:00:00Z", replies: [] }],
    citizenEngagementScore: 96,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
  },
];

// ============================
// Notifications
// ============================

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "report_update",
    title: "Raport actualizat",
    message: "Raportul tău \"SUV parcat pe pista de pe Calea Moților\" este acum în analiză.",
    read: false,
    createdAt: "2026-03-10T09:00:00Z",
    link: "/cetatean/feedback",
  },
  {
    id: "n2",
    type: "proposal_vote",
    title: "Propunere votată",
    message: "Propunerea ta \"Pistă de biciclete pe Calea Turzii\" a primit 5 voturi noi!",
    read: false,
    createdAt: "2026-03-09T18:00:00Z",
    link: "/cetatean/propuneri",
  },
  {
    id: "n3",
    type: "project_update",
    title: "Proiect actualizat",
    message: "Proiectul \"Rețea ciclabilă centru\" a trecut în faza de execuție.",
    read: true,
    createdAt: "2026-03-08T14:00:00Z",
    link: "/cetatean/proiecte",
  },
  {
    id: "n4",
    type: "badge_earned",
    title: "Insignă nouă!",
    message: "Felicitări! Ai obținut insigna \"Explorator\" — rapoarte din 5 cartiere diferite! 🗺️",
    read: true,
    createdAt: "2026-01-20T10:00:00Z",
  },
  {
    id: "n5",
    type: "system",
    title: "Bun venit la VeloCivic!",
    message: "Bine ai venit pe platforma VeloCivic. Începe prin a trimite primul tău raport!",
    read: true,
    createdAt: "2025-09-15T10:00:00Z",
  },
];

// ============================
// Activities
// ============================

export const mockActivities: Activity[] = [
  {
    id: "a1",
    userId: "u1",
    type: "report",
    description: "Ai raportat \"SUV parcat pe pista de pe Calea Moților\"",
    createdAt: "2026-03-08T10:30:00Z",
    link: "/cetatean/feedback",
  },
  {
    id: "a2",
    userId: "u1",
    type: "vote",
    description: "Ai votat propunerea \"Semafoare dedicate bicicliștilor pe Eroilor\"",
    createdAt: "2026-03-07T16:00:00Z",
    link: "/cetatean/propuneri",
  },
  {
    id: "a3",
    userId: "u1",
    type: "comment",
    description: "Ai comentat la propunerea \"Stații de biciclete securizate\"",
    createdAt: "2026-03-06T13:30:00Z",
    link: "/cetatean/propuneri",
  },
  {
    id: "a4",
    userId: "u1",
    type: "report",
    description: "Raportul \"Groapă mare pe strada Memorandumului\" a fost trimis",
    createdAt: "2026-03-07T14:20:00Z",
    link: "/cetatean/feedback",
  },
  {
    id: "a5",
    userId: "u1",
    type: "badge",
    description: "Ai obținut insigna \"Explorator\" 🗺️",
    createdAt: "2026-01-20T10:00:00Z",
  },
];

// ============================
// Dashboard Stats
// ============================

export const mockDashboardStats: DashboardStats = {
  totalReports: 1543,
  resolvedReports: 876,
  pendingReports: 234,
  averageResolutionTime: "4.2 zile",
  totalProposals: 312,
  activeProjects: 4,
  activeUsers: 8945,
  todayReports: 23,
};

export const mockCitizenStats = {
  reportsSubmitted: 8,
  proposalsVoted: 15,
  activeProjects: 2,
  pointsEarned: 1250,
};

// ============================
// Chart Data
// ============================

export const reportsByCategory = [
  { name: "Mașini parcate", value: 342 },
  { name: "Gropi", value: 256 },
  { name: "Construcții", value: 189 },
  { name: "Drum blocat", value: 156 },
  { name: "Pietoni", value: 134 },
  { name: "Obstacole", value: 178 },
  { name: "Parcări", value: 145 },
  { name: "Iluminat", value: 98 },
  { name: "Altele", value: 45 },
];

export const reportsOverTime = [
  { name: "Ian", rapoarte: 89, rezolvate: 45 },
  { name: "Feb", rapoarte: 112, rezolvate: 67 },
  { name: "Mar", rapoarte: 134, rezolvate: 89 },
  { name: "Apr", rapoarte: 156, rezolvate: 98 },
  { name: "Mai", rapoarte: 178, rezolvate: 112 },
  { name: "Iun", rapoarte: 198, rezolvate: 134 },
  { name: "Iul", rapoarte: 167, rezolvate: 145 },
  { name: "Aug", rapoarte: 145, rezolvate: 123 },
  { name: "Sep", rapoarte: 189, rezolvate: 156 },
  { name: "Oct", rapoarte: 212, rezolvate: 167 },
  { name: "Nov", rapoarte: 234, rezolvate: 189 },
  { name: "Dec", rapoarte: 198, rezolvate: 178 },
];

export const proposalsByStatus = [
  { name: "În analiză", value: 156, fill: "#00d4ff" },
  { name: "Aprobate", value: 89, fill: "#a3e635" },
  { name: "Respinse", value: 34, fill: "#ef4444" },
  { name: "În implementare", value: 33, fill: "#f59e0b" },
];

export const heatmapCalendarData = Array.from({ length: 365 }, (_, i) => {
  const date = new Date(2025, 2, 10);
  date.setDate(date.getDate() + i);
  return {
    date: date.toISOString().split("T")[0],
    count: Math.floor(Math.random() * 15),
  };
});

// ============================
// Map Layers
// ============================

export const defaultMapLayers: MapLayer[] = [
  { id: "heatmap_pericole", label: "Heatmap pericole", color: "#ef4444", icon: "🔴", visible: true },
  { id: "trafic_biciclete", label: "Trafic biciclete", color: "#f59e0b", icon: "🟡", visible: false },
  { id: "infrastructura", label: "Infrastructură existentă", color: "#a3e635", icon: "🟢", visible: true },
  { id: "proiecte", label: "Proiecte în desfășurare", color: "#00d4ff", icon: "🔵", visible: false },
  { id: "propuneri", label: "Propuneri cetățeni", color: "#a855f7", icon: "⭐", visible: false },
];

// ============================
// Simulation Scenarios
// ============================

export const mockScenarios: SimulationScenario[] = [
  {
    id: "s1",
    name: "Piste complete centru",
    description: "Rețea completă de piste de biciclete în centrul Clujului",
    metrics: { safetyScore: 92, coveragePercent: 78, conflictZones: 3, accessibilityScore: 88 },
  },
  {
    id: "s2",
    name: "Parcare maximizată",
    description: "Maximizarea parcărilor de biciclete la nodurile de transport",
    metrics: { safetyScore: 75, coveragePercent: 45, conflictZones: 12, accessibilityScore: 95 },
  },
  {
    id: "s3",
    name: "Siguranță totală",
    description: "Toate intersecțiile cu semaforizare și bariere dedicate",
    metrics: { safetyScore: 98, coveragePercent: 60, conflictZones: 1, accessibilityScore: 82 },
  },
];

// ============================
// Severity & Status Configs
// ============================

export const severityConfig = {
  scazut: { label: "Scăzut", color: "bg-blue-500/20 text-blue-400 border-blue-500/30" },
  mediu: { label: "Mediu", color: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30" },
  ridicat: { label: "Ridicat", color: "bg-orange-500/20 text-orange-400 border-orange-500/30" },
  critic: { label: "Critic", color: "bg-red-500/20 text-red-400 border-red-500/30" },
};

export const reportStatusConfig = {
  trimis: { label: "Trimis", color: "bg-slate-500/20 text-slate-400 border-slate-500/30" },
  in_analiza: { label: "În analiză", color: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30" },
  in_lucru: { label: "În lucru", color: "bg-amber-500/20 text-amber-400 border-amber-500/30" },
  rezolvat: { label: "Rezolvat", color: "bg-green-500/20 text-green-400 border-green-500/30" },
  respins: { label: "Respins", color: "bg-red-500/20 text-red-400 border-red-500/30" },
};

export const proposalStatusConfig = {
  in_analiza: { label: "În analiză", color: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30" },
  aprobat: { label: "Aprobat", color: "bg-green-500/20 text-green-400 border-green-500/30" },
  respins: { label: "Respins", color: "bg-red-500/20 text-red-400 border-red-500/30" },
  in_implementare: { label: "În implementare", color: "bg-amber-500/20 text-amber-400 border-amber-500/30" },
};

export const projectStageConfig = {
  planificat: { label: "Planificat", color: "bg-slate-500/20 text-slate-400", order: 0 },
  consultare_publica: { label: "Consultare publică", color: "bg-purple-500/20 text-purple-400", order: 1 },
  aprobare: { label: "Aprobare", color: "bg-cyan-500/20 text-cyan-400", order: 2 },
  in_lucru: { label: "În lucru", color: "bg-amber-500/20 text-amber-400", order: 3 },
  finalizat: { label: "Finalizat", color: "bg-green-500/20 text-green-400", order: 4 },
};
